/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps.poo;
import static com.sun.java.accessibility.util.AWTEventMonitor.addKeyListener;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.text.DecimalFormat;
import java.util.Random;
import static javax.management.Query.or;
/**
 * @author rodri
 */
public class Teclado extends javax.swing.JFrame {
 private final Color C1 = Color.blue;
 public contar_erros_acertos count =  new contar_erros_acertos("");
 private final Color padrão = Color.gray;  
    private int valor_certo;
    private int valor_errado;
 public void pintar_teclador()
 {
     A_B.setBackground(padrão);
     B_B.setBackground(padrão);
     C_B.setBackground(padrão);
     D_B.setBackground(padrão);
     E_B.setBackground(padrão);
     F_B.setBackground(padrão);
     G_B.setBackground(padrão);
     H_B.setBackground(padrão);
     I_B.setBackground(padrão);
     J_B.setBackground(padrão);
     L_B.setBackground(padrão);
     M_B.setBackground(padrão);
     N_B.setBackground(padrão);
     O_B.setBackground(padrão);
     P_B.setBackground(padrão);
     Q_B.setBackground(padrão);
     R_B.setBackground(padrão);
     S_B.setBackground(padrão);
     T_B.setBackground(padrão);
     U_B.setBackground(padrão);
     V_B.setBackground(padrão);
     X_B.setBackground(padrão);
     Z_B.setBackground(padrão);
     W_B.setBackground(padrão);
     Y_B.setBackground(padrão);
     K_B.setBackground(padrão);
     Ç_B.setBackground(padrão);
     UM_B.setBackground(padrão);
     Dois_B.setBackground(padrão);
     TRES_B.setBackground(padrão);
     QUATRO_B.setBackground(padrão);
     CINCO_B.setBackground(padrão);
     SEIS_B.setBackground(padrão);
     SETE_B.setBackground(padrão);
     OITO_B.setBackground(padrão);
     NOVE_B.setBackground(padrão);
     ZERO_B.setBackground(padrão);
     
 }   
  
    /**
     * Creates new form Teclado
     */
    String Pangrama[] = {"quem traz cd, lp, fax, engov e whisky jb?",
        "tv faz quengo explodir com whisky jb",
        "gafanhotos azuis celebram a pequena terra das jovens bruxas",
        "um pequeno jabuti xereta viu dez cegonhas felizes"};
    public Teclado() {
        initComponents();
         tela_de_texto.setEnabled(false);
         Final_b.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        UM_B = new javax.swing.JButton();
        Q_B = new javax.swing.JButton();
        W_B = new javax.swing.JButton();
        Dois_B = new javax.swing.JButton();
        TRES_B = new javax.swing.JButton();
        QUATRO_B = new javax.swing.JButton();
        CINCO_B = new javax.swing.JButton();
        SEIS_B = new javax.swing.JButton();
        SETE_B = new javax.swing.JButton();
        OITO_B = new javax.swing.JButton();
        NOVE_B = new javax.swing.JButton();
        E_B = new javax.swing.JButton();
        R_B = new javax.swing.JButton();
        T_B = new javax.swing.JButton();
        Y_B = new javax.swing.JButton();
        U_B = new javax.swing.JButton();
        I_B = new javax.swing.JButton();
        O_B = new javax.swing.JButton();
        P_B = new javax.swing.JButton();
        A_B = new javax.swing.JButton();
        S_B = new javax.swing.JButton();
        D_B = new javax.swing.JButton();
        F_B = new javax.swing.JButton();
        G_B = new javax.swing.JButton();
        H_B = new javax.swing.JButton();
        J_B = new javax.swing.JButton();
        K_B = new javax.swing.JButton();
        L_B = new javax.swing.JButton();
        Ç_B = new javax.swing.JButton();
        Z_B = new javax.swing.JButton();
        X_B = new javax.swing.JButton();
        C_B = new javax.swing.JButton();
        V_B = new javax.swing.JButton();
        B_B = new javax.swing.JButton();
        N_B = new javax.swing.JButton();
        M_B = new javax.swing.JButton();
        ZERO_B = new javax.swing.JButton();
        Iniciar_b = new javax.swing.JButton();
        tela_de_texto = new javax.swing.JTextField();
        Panagrama_aparecer = new javax.swing.JLabel();
        Final_b = new javax.swing.JButton();

        jButton13.setText("E");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UM_B.setText("1");

        Q_B.setText("q");

        W_B.setText("W");

        Dois_B.setText("2");

        TRES_B.setText("3");

        QUATRO_B.setText("4");

        CINCO_B.setText("5");

        SEIS_B.setText("6");

        SETE_B.setText("7");

        OITO_B.setText("8");

        NOVE_B.setText("9");

        E_B.setText("E");

        R_B.setText("R");

        T_B.setText("T");

        Y_B.setText("Y");

        U_B.setText("U");

        I_B.setText("I");

        O_B.setText("O");

        P_B.setText("P");

        A_B.setText("A");

        S_B.setText("S");

        D_B.setText("D");

        F_B.setText("F");

        G_B.setText("G");

        H_B.setText("H");

        J_B.setText("J");

        K_B.setText("K");

        L_B.setText("L");

        Ç_B.setText("Ç");

        Z_B.setText("Z");

        X_B.setText("X");

        C_B.setText("C");

        V_B.setText("V");

        B_B.setText("B");

        N_B.setText("N");

        M_B.setText("M");

        ZERO_B.setText("0");

        Iniciar_b.setText("Iniciar");
        Iniciar_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_bActionPerformed(evt);
            }
        });

        tela_de_texto.setText("Aperte O Botão iniciar");
        tela_de_texto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tela_de_textoCaretUpdate(evt);
            }
        });
        tela_de_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tela_de_textoActionPerformed(evt);
            }
        });
        tela_de_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tela_de_textoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tela_de_textoKeyReleased(evt);
            }
        });

        Final_b.setText("Final");
        Final_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Final_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Q_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(W_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Y_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(O_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P_B))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UM_B, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Dois_B, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TRES_B, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QUATRO_B, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CINCO_B, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SEIS_B, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SETE_B, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OITO_B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NOVE_B, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZERO_B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Iniciar_b, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Final_b, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(A_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(S_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(F_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(G_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(H_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(J_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(K_B))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Z_B)
                                        .addGap(18, 18, 18)
                                        .addComponent(X_B)
                                        .addGap(18, 18, 18)
                                        .addComponent(C_B)
                                        .addGap(18, 18, 18)
                                        .addComponent(V_B)
                                        .addGap(18, 18, 18)
                                        .addComponent(B_B)
                                        .addGap(18, 18, 18)
                                        .addComponent(N_B)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(L_B)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Ç_B))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(M_B)))))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Panagrama_aparecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tela_de_texto, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panagrama_aparecer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tela_de_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOVE_B)
                    .addComponent(OITO_B)
                    .addComponent(SETE_B)
                    .addComponent(SEIS_B)
                    .addComponent(CINCO_B)
                    .addComponent(QUATRO_B)
                    .addComponent(TRES_B)
                    .addComponent(Dois_B)
                    .addComponent(UM_B)
                    .addComponent(ZERO_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q_B)
                    .addComponent(W_B)
                    .addComponent(E_B)
                    .addComponent(R_B)
                    .addComponent(T_B)
                    .addComponent(Y_B)
                    .addComponent(U_B)
                    .addComponent(I_B)
                    .addComponent(O_B)
                    .addComponent(P_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A_B)
                    .addComponent(S_B)
                    .addComponent(D_B)
                    .addComponent(F_B)
                    .addComponent(G_B)
                    .addComponent(H_B)
                    .addComponent(J_B)
                    .addComponent(K_B)
                    .addComponent(L_B)
                    .addComponent(Ç_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Z_B)
                    .addComponent(X_B)
                    .addComponent(C_B)
                    .addComponent(V_B)
                    .addComponent(B_B)
                    .addComponent(N_B)
                    .addComponent(M_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Iniciar_b, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Final_b, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getPanangrama()
    {
        Random rand = new Random();
        return Pangrama[rand.nextInt(4)];
        
    }
    
     String pan;
    
    private void Iniciar_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_bActionPerformed
        tela_de_texto.setEnabled(true);
        tela_de_texto.setText("");
        pintar_teclador();
        pan = getPanangrama();
        Panagrama_aparecer.setText(pan);
        count.getEscrita();
        count.zerar();
        Iniciar_b.setEnabled(false);
        count.tamanho_pan(pan);
        count.zerar();
        Final_b.setEnabled(true);
    }//GEN-LAST:event_Iniciar_bActionPerformed

    private void tela_de_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tela_de_textoActionPerformed
        
        
    }//GEN-LAST:event_tela_de_textoActionPerformed

    private void tela_de_textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tela_de_textoKeyPressed
        switch (evt.getKeyCode()) {//verifica se a tecla pressionada é o BACKSPACE
            case KeyEvent.VK_A:
                 pintar_teclador();
                 A_B.setBackground(C1);
                 
                 break;
            case KeyEvent.VK_B:
                pintar_teclador();
                 B_B.setBackground(C1);
                 
                 break;
            case KeyEvent.VK_C:
                pintar_teclador();
                 C_B.setBackground(C1);
                 
                  break;
            case KeyEvent.VK_D:
                pintar_teclador();
                D_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_E:
                pintar_teclador();
                E_B.setBackground(C1);
               
                break;
            case KeyEvent.VK_F:
                pintar_teclador();
                F_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_G:
                pintar_teclador();
                G_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_H:
                pintar_teclador();
                H_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_I:
                pintar_teclador();
                I_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_J:
                pintar_teclador();
                J_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_L:
                pintar_teclador();
                L_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_M:
                pintar_teclador();
                M_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_N:
                pintar_teclador();
                N_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_O:
                pintar_teclador();
                O_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_P:
                pintar_teclador();
                P_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_Q:
                pintar_teclador();
                Q_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_R:
                pintar_teclador();
                R_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_S:
                pintar_teclador();
                S_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_T:
                pintar_teclador();
                T_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_U:
                pintar_teclador();
                U_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_V:
                pintar_teclador();
                V_B.setBackground(C1);
                
                break;
           case KeyEvent.VK_X:
                pintar_teclador();
                X_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_Z:
                pintar_teclador();
                Z_B.setBackground(C1);
                
                break;   
            case KeyEvent.VK_Y:
                pintar_teclador();
                Y_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_K:
                pintar_teclador();
                K_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_W:
                pintar_teclador();
                W_B.setBackground(C1);
                
                break;
            case KeyEvent.VK_1:
                pintar_teclador();
                UM_B.setBackground(C1);
                break;
            case KeyEvent.VK_2:
                pintar_teclador();
                Dois_B.setBackground(C1);
                break;
            case KeyEvent.VK_3:
                pintar_teclador();
                TRES_B.setBackground(C1);
                break;
            case KeyEvent.VK_4:
                pintar_teclador();
                QUATRO_B.setBackground(C1);
                break;
            case KeyEvent.VK_5:
                pintar_teclador();
                CINCO_B.setBackground(C1);
                break;
            case KeyEvent.VK_6:
                pintar_teclador();
                SEIS_B.setBackground(C1);
                break;
            case KeyEvent.VK_7:
                pintar_teclador();
                SETE_B.setBackground(C1);
                break;
            case KeyEvent.VK_8:
                pintar_teclador();
                OITO_B.setBackground(C1);
                break;
            case KeyEvent.VK_9:
                pintar_teclador();
                NOVE_B.setBackground(C1);
                break;
            case KeyEvent.VK_0:
                pintar_teclador();
                ZERO_B.setBackground(C1);
                break;
            default:
                pintar_teclador();
                break;
        }
    }//GEN-LAST:event_tela_de_textoKeyPressed

    private void tela_de_textoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tela_de_textoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tela_de_textoKeyReleased

    private void Final_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Final_bActionPerformed
            if (tela_de_texto.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(this,"a sua porcentagem de acerto foi de 0 %");
            JOptionPane.showMessageDialog(this,"a sua porcentagem de erros foi 100.00 %");
                
            }
            else{
            DecimalFormat df = new DecimalFormat("0.00");
            float total_tudo = (valor_certo + valor_errado);
            float total_certo = (valor_certo/total_tudo) * 100;
            float total_erros = 100 - total_certo;
            JOptionPane.showMessageDialog(this,"a sua porcentagem de acerto foi de " +df.format(total_certo)+"%");
            JOptionPane.showMessageDialog(this,"a sua porcentagem de erros foi " + df.format(total_erros)+"%");
            total_certo = 0;
            total_erros = 0;
            total_tudo = 0;
            }
            Iniciar_b.setEnabled(true);
            tela_de_texto.setEnabled(false);
            Panagrama_aparecer.setText("");
            tela_de_texto.setText("");
            Final_b.setEnabled(false);
            
    }//GEN-LAST:event_Final_bActionPerformed

    private void tela_de_textoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tela_de_textoCaretUpdate
        int tamanho = 0;
        if(tela_de_texto.getText().length() != 0)
        {
            tamanho = tela_de_texto.getText().length();
            if (count.contagem(Panagrama_aparecer.getText(),tela_de_texto.getText().charAt(tamanho-1), tela_de_texto.getText()))
        {
            valor_certo = count.getAcertos();
        }
        else
        {
            valor_errado = count.getErros();
        }
           
        }
        
    }//GEN-LAST:event_tela_de_textoCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teclado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_B;
    private javax.swing.JButton B_B;
    private javax.swing.JButton CINCO_B;
    private javax.swing.JButton C_B;
    private javax.swing.JButton D_B;
    private javax.swing.JButton Dois_B;
    private javax.swing.JButton E_B;
    private javax.swing.JButton F_B;
    private javax.swing.JButton Final_b;
    private javax.swing.JButton G_B;
    private javax.swing.JButton H_B;
    private javax.swing.JButton I_B;
    private javax.swing.JButton Iniciar_b;
    private javax.swing.JButton J_B;
    private javax.swing.JButton K_B;
    private javax.swing.JButton L_B;
    private javax.swing.JButton M_B;
    private javax.swing.JButton NOVE_B;
    private javax.swing.JButton N_B;
    private javax.swing.JButton OITO_B;
    private javax.swing.JButton O_B;
    private javax.swing.JButton P_B;
    private javax.swing.JLabel Panagrama_aparecer;
    private javax.swing.JButton QUATRO_B;
    private javax.swing.JButton Q_B;
    private javax.swing.JButton R_B;
    private javax.swing.JButton SEIS_B;
    private javax.swing.JButton SETE_B;
    private javax.swing.JButton S_B;
    private javax.swing.JButton TRES_B;
    private javax.swing.JButton T_B;
    private javax.swing.JButton UM_B;
    private javax.swing.JButton U_B;
    private javax.swing.JButton V_B;
    private javax.swing.JButton W_B;
    private javax.swing.JButton X_B;
    private javax.swing.JButton Y_B;
    private javax.swing.JButton ZERO_B;
    private javax.swing.JButton Z_B;
    private javax.swing.JButton jButton13;
    private javax.swing.JTextField tela_de_texto;
    private javax.swing.JButton Ç_B;
    // End of variables declaration//GEN-END:variables
}
